Updated about
workshopapps/investment.web pull request #292
Opened 2022-12-13 13:11 UTC by chiomaubaezuonu

Added About page

2022-12-13 14:32 UTC, JayCodist approved these changes

2022-12-13 18:30 UTC, isoteriksoftware requested changes

2022-12-13 18:30 UTC, isoteriksoftware commented on frontend_next/components/about/MiddleSection.jsx
> +                <img src={WhyChooseUs.src} className="mt-5 md:w-[564px]" />
Please add alt attribute to your images else it won't run on the server

2022-12-13 18:30 UTC, isoteriksoftware commented on frontend_next/components/about/MiddleSection.jsx
> +                <img src={WhyChooseUs.src} className="mt-6 md:w-[564px]" />
same here

2022-12-13 19:26 UTC, chiomaubaezuonu commented on frontend_next/components/about/MiddleSection.jsx
> +                <img src={WhyChooseUs.src} className="mt-6 md:w-[564px]" />
Done

2022-12-14 09:49 UTC, isoteriksoftware approved these changes

2022-12-14 09:49 UTC, merged